### ISSUE TITLE
Report of the problem in the StackStorm-Exchange page

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/web#21]
Dear, all

I couldn't access the [StackStorm-Exchange/exchange-template](https://github.com/StackStorm-Exchange/exchange-template) repository which is specified in [here](https://github.com/StackStorm-Exchange/web/blob/48ce3a567f66f02dbb182b5843106b1e593f42bc/src/components/PackButtons/index.jsx#L44-L49).

When I access to that repository, I could see the GitHub 404 page.
I don't know whether this is because of an erroneous URL description or permission.

Thank you.

**Comment by emedvedev** [comment]
Thanks for the report! We'll fix as soon as we can :)


On February 13, 2017 at 11:15:36, Hiroyasu OHYAMA (notifications@github.com)
wrote:

Hi, team

I couldn't access the StackStorm-Exchange/exchange-tesmplte
<https://github.com/StackStorm-Exchange/exchange-template> repository which
is specified in here
<https://github.com/StackStorm-Exchange/web/blob/48ce3a567f66f02dbb182b5843106b1e593f42bc/src/components/PackButtons/index.jsx#L44-L49>
.

When I access to that repository, I could see the GitHub 404 page.
I don't know whether this is because of an erroneous URL description or
permission.

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackStorm-Exchange/web/issues/21>, or mute the thread

**Comment by LindsayHill** [comment]
Basic template repository added
